// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmu-SUZbf6gUeTp3eqWgnLebdHFzqR-5s',
    appId: '1:269639114847:web:acbb0c93b1fe72a5397bea',
    messagingSenderId: '269639114847',
    projectId: 'healsearch-6565e',
    authDomain: 'healsearch-6565e.firebaseapp.com',
    storageBucket: 'healsearch-6565e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDulVR9UD11zhJ2gUuyPYe42Srpd4X21G8',
    appId: '1:269639114847:android:a3d587be11d55106397bea',
    messagingSenderId: '269639114847',
    projectId: 'healsearch-6565e',
    storageBucket: 'healsearch-6565e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0quk2RaCUdy80ocUEihRcOTqPMSJiHhs',
    appId: '1:269639114847:ios:24c79870d0196666397bea',
    messagingSenderId: '269639114847',
    projectId: 'healsearch-6565e',
    storageBucket: 'healsearch-6565e.firebasestorage.app',
    androidClientId: '269639114847-557tekrq9e1bqkct9clhlqibvjqhmuvk.apps.googleusercontent.com',
    iosClientId: '269639114847-hvjngq0g0028q042877nh44fhg7bmqbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktopSearchAHolic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0quk2RaCUdy80ocUEihRcOTqPMSJiHhs',
    appId: '1:269639114847:ios:24c79870d0196666397bea',
    messagingSenderId: '269639114847',
    projectId: 'healsearch-6565e',
    storageBucket: 'healsearch-6565e.firebasestorage.app',
    androidClientId: '269639114847-557tekrq9e1bqkct9clhlqibvjqhmuvk.apps.googleusercontent.com',
    iosClientId: '269639114847-hvjngq0g0028q042877nh44fhg7bmqbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.desktopSearchAHolic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmu-SUZbf6gUeTp3eqWgnLebdHFzqR-5s',
    appId: '1:269639114847:web:9165259910c6bfaa397bea',
    messagingSenderId: '269639114847',
    projectId: 'healsearch-6565e',
    authDomain: 'healsearch-6565e.firebaseapp.com',
    storageBucket: 'healsearch-6565e.firebasestorage.app',
  );
}
